### ISSUE TITLE
Touch support clobbers mouse drag support

### ISSUE THREAD

**Issue by appsforartists** [liftoff/HumanInput#3]
In the [pan demo](https://liftoff.github.io/HumanInput/demo/pan/), I can pan with my touchscreen on my Chromebook Pixel, but clicking and dragging does nothing.

**Comment by liftoff** [comment]
Interesting.  I don't have a device that has both a touchscreen _and_ a mouse.  I'll see what I can do to emulate that situation and get to the bottom of it.

Does the problem still happen if you enable Pointer Event support?  If you open chrome://flags on your Chromebook Pixel you should see a "Pointer Events" option.  The "default" option is actually, "disabled" (it's a bad/unclear interface) so make sure you set it to "enabled".  Once that's done please try the pan demo again and report back what you find.

I'll see what I can do in the mean time to figure it out.  I suspect the problem is in the _pointerdown() function...

```
if (changedTouches && changedTouches.length) {
// ...code here
// Disable mouse events since we're going to be handling everything via touch
noMouseEvents = true;
```

I'm guessing that the touch event on your Chromebook is firing when you use the mouse even though you're not touching the screen.  Either that or the "changedTouches" attribute is somehow winding up on the mouse event.

**Comment by liftoff** [comment]
I believe I've figured this one out.  I was able to reproduce the problem by emulating touch events on my desktop in Chrome and then switching between mouse and touch via the "device toolbar" option in the developer tools.

I just pushed v1.1.12 which should correct the issue.  Can you grab the latest code and give it a try?  Thanks.

**Comment by appsforartists** [comment]
The demo in the linked in the OP is still broken.  Did you update it?

**Comment by liftoff** [comment]
No, I haven't updated the demo yet because I was waiting to hear back to see if it was fixed :smile: 

I'll update the demo site soon.

**Comment by appsforartists** [comment]
I haven't used HumanInput except playing with the demo.  :embarrassed:

**Comment by liftoff** [comment]
I'm going to close this issue since I'm *90% certain* it was fixed in version 1.1.12.  Also, no one has reported the issue since.
